config/routes.rb
Grill::Application.routes.draw do

  resources :orders, only: [:edit, :update, :destroy]

  get '/checkout' => 'orders#edit', as: 'checkout'
  
  resources :order_items
  resources :reservations

  get "login" => 'sessions#new', as: :sign_in
  post "sessions" => 'sessions#create' 
  get "logout" => 'sessions#destroy', as: :sign_out

  resources :users
  resources :items

  root to: 'pages#home'
  get '/menu' => 'pages#menu', as: 'menu'


  # Original Mockups:
  
  get '/mockup/home' => 'mockup#home'
  get '/help' => 'mockup#help'
  get "/location" => 'mockup#location', as: 'location'
  get "/mockup/menu" => 'mockup#menu'
  get "/orders/new" => 'mockup#ordering', as: 'new_order'
  get "/reservations/new" => 'mockup#reservations', as: 'new_reservation'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grill</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Trade+Winds' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <header>
      <h1><%= link_to "Starter Grill", root_url %></h1>
      <% if current_user %>
        <h2>Hello, <%= current_user.name %>!</h2>
      <% end %>
      <nav>
        <ul>
          <li><%= link_to 'Menu', menu_url %></li>
          <li><%= link_to 'Location', location_url %></li>
          <li><%= link_to 'Reservations', new_reservation_url %></li>
          <% if current_user %>
            <li><%= link_to "Sign Out", sign_out_url %></li>
            <li><%= link_to "My Profile", user_url(current_user.id) %></li>
            <li><%= link_to "My Order (#{pluralize(current_order.order_items.count, 'Item')})", checkout_url %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_url %></li>
            <li><%= link_to "Sign In", sign_in_url %></li>
          <% end %>
          <li><%= link_to 'Help', help_url %></li>
        </ul>
      </nav>
    </header>
  
    <div class="content">
      <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p>
      <% end %>
      <%= yield %>
    </div>
    
    <footer>
      &copy;2012 The Starter Grill, Inc.  All rights reversed.  Got a comment? Keep it to yourself!
    </footer>
  </div>
    
</body>
</html>